#General/Misc Config
DEBUG: True
LOGLEVEL: 'INFO'
UPLOADS_DEFAULT_DEST: "/tmp"

SQLALCHEMY_DATABASE_URI: 'postgres://postgres:@db:5432/postgres'

#Salt and Pepper
SECRET_KEY: '\xd0\xb9U\xff\x96\x9dG\x89\x17\x1e\x8d\xb0\xac[\xdc*\x0ejV\xea2(\x0f\xf3'
AES_KEY: '61ec0dfd-3007-431e-b20c-7d5d44e89e7a'

SECURITY_REGISTERABLE: True
SECURITY_RECOVERABLE: True
SECURITY_TRACKABLE: True
SECURITY_CHANGEABLE: True
SECURITY_PASSWORD_HASH: bcrypt
SECURITY_PASSWORD_SALT: 'bb83d6fa8d0a4adc'
SECURITY_SEND_REGISTER_EMAIL: False

SECURITY_EMAIL_SENDER: noreply@networkofinnovators.org
SECURITY_POST_REGISTER_VIEW: 'views.my_profile'
SECURITY_POST_CONFIRM_VIEW: 'views.my_profile'
SECURITY_POST_LOGIN_VIEW: 'views.match'
SECURITY_EMAIL_SUBJECT_REGISTER: 'Welcome to the Network of Innovators!'
SECURITY_EMAIL_SUBJECT_PASSWORD_NOTICE: 'Your Network of Innovators password has been reset'
SECURITY_EMAIL_SUBJECT_PASSWORD_CHANGE_NOTICE: 'Your Network of Innovators password has been changed'
SECURITY_EMAIL_SUBJECT_PASSWORD_RESET: 'Network of Innovators password reset instructions'
SECURITY_EMAIL_SUBJECT_CONFIRM: 'Please confirm your email for Network of Innovators'

MAIL_SERVER: 'smtp.gmail.com'
MAIL_PORT: 587
MAIL_USE_SSL: False
MAIL_USE_TLS: True

S3_BUCKET_NAME: 'network-of-innovators'

CELERY_TIMEZONE: 'UTC'

NOI_DEPLOY: '_default'
