#General/Misc Config
DEBUG: True
LOGLEVEL: 'INFO'
UPLOADS_DEFAULT_DEST: "/tmp"

SQLALCHEMY_DATABASE_URI: 'postgres://postgres:@db:5432/postgres'

#Salt and Pepper
SECRET_KEY: '\xd0\xb9U\xff\x96\x9dG\x89\x17\x1e\x8d\xb0\xac[\xdc*\x0ejV\xea2(\x0f\xf3'
AES_KEY: '61ec0dfd-3007-431e-b20c-7d5d44e89e7a'

DEBUG_TB_INTERCEPT_REDIRECTS: False
CACHE_TYPE: simple

SECURITY_REGISTERABLE: True
SECURITY_RECOVERABLE: True
SECURITY_TRACKABLE: True
SECURITY_CHANGEABLE: True
SECURITY_PASSWORD_HASH: bcrypt
SECURITY_PASSWORD_SALT: 'bb83d6fa8d0a4adc'
SECURITY_SEND_REGISTER_EMAIL: False
SECURITY_CONFIRMABLE: True
SECURITY_LOGIN_WITHOUT_CONFIRMATION: True

# This is a workaround for
# https://github.com/mattupstate/flask-security/pull/489.
SECURITY_MSG_CONFIRM_REGISTRATION: ['DO_NOT_DISPLAY_ME', 'success']

SECURITY_EMAIL_SENDER: noreply@networkofinnovators.org
SECURITY_POST_REGISTER_VIEW: 'views.register_step_2'
SECURITY_POST_CONFIRM_VIEW: 'views.confirmation_success'
SECURITY_POST_LOGIN_VIEW: 'views.activity'
SECURITY_EMAIL_SUBJECT_REGISTER: 'Welcome to the Network of Innovators!'
SECURITY_EMAIL_SUBJECT_PASSWORD_NOTICE: 'Your Network of Innovators password has been reset'
SECURITY_EMAIL_SUBJECT_PASSWORD_CHANGE_NOTICE: 'Your Network of Innovators password has been changed'
SECURITY_EMAIL_SUBJECT_PASSWORD_RESET: 'Network of Innovators password reset instructions'
SECURITY_EMAIL_SUBJECT_CONFIRM: 'Please confirm your email for Network of Innovators'

S3_BUCKET_NAME: 'network-of-innovators'
USE_S3: False

NOI_DEPLOY: '_default'
