"""Adding tutorial step column to user

Revision ID: 1e1fc3825671
Revises: 49f54a337616
Create Date: 2015-10-07 16:19:44.029086

"""

# revision identifiers, used by Alembic.
revision = '1e1fc3825671'
down_revision = '49f54a337616'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tutorial_step', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tutorial_step')
    ### end Alembic commands ###
