"""add post_number column to discourse_topics

Revision ID: 28ff85fcc188
Revises: 312a48268855
Create Date: 2016-03-22 22:00:07.520355

"""

# revision identifiers, used by Alembic.
revision = '28ff85fcc188'
down_revision = '312a48268855'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discourse_topics', sa.Column('post_number', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discourse_topics', 'post_number')
    ### end Alembic commands ###
