"""Add user_conferences table.

Revision ID: 4a023d26bf06
Revises: 51bdb7c7928a
Create Date: 2016-04-19 14:04:23.365268

"""

# revision identifiers, used by Alembic.
revision = '4a023d26bf06'
down_revision = '51bdb7c7928a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_conferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference', sa.Unicode(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'conference')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_conferences')
    ### end Alembic commands ###
