"""empty message

Revision ID: 902e1bf2855
Revises: 4a023d26bf06
Create Date: 2016-05-23 22:26:19.279163

"""

# revision identifiers, used by Alembic.
revision = '902e1bf2855'
down_revision = '4a023d26bf06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
